version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $APP_IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $APP_IMAGE_NAME:latest $APP_IMAGE_NAME:$CIRCLE_SHA1
            docker push $APP_IMAGE_NAME:latest
            docker push $APP_IMAGE_NAME:$CIRCLE_SHA1
workflows:
  version: 2
  build-testing:
    jobs:
      - build:
          filters:
            branches:
              only: master
